# Generated by Django 3.0.7 on 2020-06-08 06:31

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sum_content',
            field=django_summernote.fields.SummernoteTextField(default='test 2'),
            preserve_default=False,
        ),
    ]
